name: Docker Build, Prisma & Sysdig Scan

on:
  push:
    branches:
      - main

jobs:
  docker-build-scan:
    name: Docker Build and Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
      id-token: write

    env:
      DOCKER_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}
      IMAGE_NAME: camping-application
      IMAGE_TAG: ${{ github.run_number }}
      FULL_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/camping-application:${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.FULL_IMAGE_NAME }}

      - name: Prisma Cloud Image Scan - NonProd
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.6.4
        with:
          pcc_console_url: https://asia-south1.cloud.twistlock.com/india-1131963775
          pcc_user: ${{ secrets.pcc_user }}
          pcc_pass: ${{ secrets.pcc_pass }}
          image_name: ${{ env.FULL_IMAGE_NAME }}

      - name: Sysdig Image Scan
        id: sysdig-scan
        uses: sysdiglabs/scan-action@v5
        with:
          image-tag: ${{ env.FULL_IMAGE_NAME }}
          sysdig-secure-token: 5998118c-eea1-4358-905f-2b770a28ce86
          sysdig-secure-url: https://app.in1.sysdig.com
          severity-at-least: low
          stop-on-failed-policy-eval: true
          stop-on-processing-error: true
          group-by-package: true
          use-policies: true
          override-pullstring: ${{ env.FULL_IMAGE_NAME }}

      - name: Upload SARIF Report to GitHub Security Tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json
